### ISSUE TITLE
using defs() draggin is broken

### ISSUE THREAD

**Issue by fibo** [wout/svg.draggable.js#14]
Hi, thank your for svg.js !

I found this issue

    var draw = SVG('canvas');
    var pin = draw.defs().circle(10).fill('orange');
    var in1 = draw.use(pin).move(100,100).draggable();

This code will produce a strange dragging.

**Comment by Quazistax** [comment]
When shape elements in `<defs>` have (x,y) != (0,0) dragging their `<use>` elements produces dislocation at the beginning of the drag operation:
http://jsfiddle.net/YsMtG/1/
```javascript
var draw = SVG('canvas').size('100%', 400);

var rpin = draw.defs().rect(60, 100).move(-30, -50).fill('#088');
var ruse = draw.use(rpin).move(100,100).draggable();  

var pin = draw.defs().circle(50).cx(0).cy(0).fill('orange'); //setting center to (0,0) sets (x,y) to (-25,-25)
var use = draw.use(pin).move(100,100).draggable();
```
That is because x,y of `<use>` element are translation values applied to referenced shape elements
http://www.w3.org/TR/SVG11/struct.html#UseElement

I solved it by checking if element is SVG.Use and using its x,y attributes for startPosition:
(in svg.draggable.js)
```javascript
/* get element bounding box */
      box = element.bbox()
      
      // added next 4 lines
      if (element instanceof SVG.Use) {  
        box.x = element.x()
        box.y = element.y()
      } else
      if (element instanceof SVG.G) {
```

**Comment by Fuzzyma** [comment]
This fix is used in the new version. Thanks for that!
